"""
Initial migration for the ``purchasing`` app.

Creates ``purchase_orders`` and ``purchase_order_items`` (CPMAS-30:
Purchase Order Management). Depends on suppliers, taxes, users, and
inventory's initial migrations for their respective foreign-key targets.

Field set and constraints (including the CASCADE on
purchase_order_items.purchase_order, the UNIQUE on
purchase_orders.po_number, and the created_by column having no _id
suffix -- unlike this schema's other FK columns) were verified against
the live Supabase database before this migration was written, since both
tables already exist there (provisioned directly via SQL). This
migration is applied there with ``--fake-initial`` rather than executed,
since the tables pre-exist; it still runs normally (creates the tables)
on any fresh environment.

Auto-generated by ``manage.py makemigrations``; do not hand-edit the
field definitions -- only this docstring was added on top.
"""
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_warehouse_stockmovement_stock'),
        ('suppliers', '0001_initial'),
        ('taxes', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('po_number', models.CharField(max_length=100, unique=True)),
                ('order_date', models.DateField()),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders_created', to='users.user')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'db_table': 'purchase_orders',
                'ordering': ['-order_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='inventory.material')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchasing.purchaseorder')),
                ('tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_items', to='taxes.taxrate')),
            ],
            options={
                'verbose_name': 'Purchase Order Item',
                'verbose_name_plural': 'Purchase Order Items',
                'db_table': 'purchase_order_items',
            },
        ),
    ]
