"""
Migration for the ``purchasing`` app: goods receiving (CPMAS-31).

Creates ``goods_receipts`` and ``goods_receipt_items``. Field set and
constraints (CASCADE on goods_receipt_items.goods_receipt, UNIQUE on
goods_receipts.receipt_number, no updated_at on goods_receipts) were
verified against the live Supabase database before this migration was
written, since both tables already exist there (provisioned directly via
SQL). Applied there with ``--fake`` (not the app's first/initial
migration, so ``--fake-initial`` doesn't apply); runs normally (creates
the tables) on any fresh environment.

Auto-generated by ``manage.py makemigrations``; do not hand-edit the
field definitions -- only this docstring was added on top.
"""
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_warehouse_stockmovement_stock'),
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(max_length=100, unique=True)),
                ('received_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='purchasing.purchaseorder')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Goods Receipt',
                'verbose_name_plural': 'Goods Receipts',
                'db_table': 'goods_receipts',
                'ordering': ['-received_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_received', models.DecimalField(decimal_places=3, max_digits=18)),
                ('notes', models.TextField(blank=True, null=True)),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchasing.goodsreceipt')),
                ('purchase_order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_items', to='purchasing.purchaseorderitem')),
            ],
            options={
                'verbose_name': 'Goods Receipt Item',
                'verbose_name_plural': 'Goods Receipt Items',
                'db_table': 'goods_receipt_items',
            },
        ),
    ]
