"""
Migration for the ``projects`` app: adds Budget/Phase/BudgetItem
(project budgeting), plus a Meta-options tweak on Project/
ProjectEmployee.

Generated after the fact -- these three models (and their db_table
Meta) already existed in apps/projects/models.py from an earlier "added
project budgeting" commit, but no migration had ever been created for
them, so `manage.py test` failed to build project_budgets/project_phases
/budget_items in the SQLite test DB (discovered while adding CPMAS-22's
notifications.services.budget_overrun_alerts, which reads these tables).

All three tables (``project_budgets``, ``project_phases``,
``budget_items``) already exist in the live Supabase database,
provisioned by the canonical SQL script. Applied against the live
database with ``--fake`` (structure already matches); runs normally
(creates the tables) on any fresh environment, e.g. the in-memory
SQLite test DB.

Auto-generated by ``manage.py makemigrations``; do not hand-edit the
field definitions -- only this docstring was added on top.
"""
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='projectemployee',
            options={},
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('REVISED', 'Revised'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='projects.project')),
            ],
            options={
                'db_table': 'project_budgets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('responsible_emp_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold')], default='NOT_STARTED', max_length=20)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('sequence_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='projects.project')),
            ],
            options={
                'db_table': 'project_phases',
                'ordering': ['project_id', 'sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('MATERIALS', 'Materials'), ('LABOR', 'Labor'), ('CONTRACTORS', 'Contractors'), ('EQUIPMENT', 'Equipment'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('budgeted_amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('budget', models.ForeignKey(db_column='budget_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='projects.budget')),
                ('phase', models.ForeignKey(blank=True, db_column='phase_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_items', to='projects.phase')),
            ],
            options={
                'db_table': 'budget_items',
            },
        ),
    ]
