# Generated by Django 5.2.17 on 2026-09-03 15:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('projects', '0002_alter_project_options_alter_projectemployee_options_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='buyer_id',
        ),
        migrations.AddField(
            model_name='project',
            name='buyer',
            field=models.ForeignKey(blank=True, db_column='buyer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='clients.client'),
        ),
        migrations.AddField(
            model_name='projectemployee',
            name='project',
            field=models.ForeignKey(db_column='project_id', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='projects.project'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='projectemployee',
            unique_together={('project', 'employee_id')},
        ),
        migrations.CreateModel(
            name='ChangeOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, db_column='approved_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_orders_approved', to='users.user')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='change_orders', to='projects.project')),
                ('requested_by', models.ForeignKey(blank=True, db_column='requested_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_orders_requested', to='users.user')),
            ],
            options={
                'db_table': 'change_orders',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
