"""
Django settings for construction project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys

from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Domain apps (accounting, inventory, projects, ...) live under BASE_DIR/apps
# instead of the project root, per the BRD's requirement to split models
# across domain-specific Django apps. Adding this directory to sys.path lets
# each app be registered in INSTALLED_APPS by its short name (e.g.
# "inventory") rather than the more verbose "apps.inventory" dotted path.
sys.path.insert(0, str(BASE_DIR / "apps"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Required (not defaulted) on purpose -- see .env.example -- so a
# deployment can't silently run with the Django-generated placeholder key
# scaffolding ships with.
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() in ("1", "true", "yes", "on")

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',

    # Domain apps registered so far (Sprint 2: CPMAS-28 Material Management,
    # CPMAS-29 Inventory & Warehouse Management, CPMAS-30 Purchase Order
    # Management, CPMAS-31 Goods Receiving, CPMAS-32 Supplier Invoices,
    # CPMAS-33 Expense Management, CPMAS-34 Accounting / Financial
    # Transactions, CPMAS-35 Accounts Receivable & Accounts Payable,
    # CPMAS-21 Receipts, CPMAS-22 Notifications --
    # plus projects/clients from CPMAS-47, built by Nireez).
    # taxes, suppliers, and users are wired in here only as minimal FK
    # targets required by apps.inventory (Material.tax_rate/default_supplier,
    # StockMovement.user) and apps.purchasing (PurchaseOrder.created_by,
    # PurchaseOrderItem.tax_rate); their own management APIs are separate,
    # unassigned/other-owner tickets and are not built here. users.User is
    # additionally managed=False -- it reflects an existing table this app
    # doesn't own the lifecycle of.
    'apps.core',
    'taxes',
    'suppliers',
    'users',
    'inventory',
    'purchasing',
    'invoicing',
    'projects',
    'clients',
    'contractors',
    'employees',
    'company',
    'expenses',
    'accounting',
    'payments',
    'notifications',
    'documents',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'users.middleware.JwtCookieRefreshMiddleware',
    'users.middleware.AppUserSessionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'construction.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'construction.context_processors.app_user',
                'construction.context_processors.company_logo',
            ],
        },
    },
]

WSGI_APPLICATION = 'construction.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
        "OPTIONS": {
            "sslmode": os.getenv("DB_SSLMODE", "require"),
        },
    }
}

# `manage.py test` runs against an in-memory SQLite database instead of
# the configured Postgres/Supabase connection. Reasons:
# 1. The test suite must run with zero setup (no live DB credentials,
#    works in CI) -- it shouldn't depend on a shared Supabase instance
#    being reachable or on the connection user having CREATEDB rights
#    (needed for Django's normal "create a throwaway test_<dbname>"
#    behavior, which the Supabase pooler connection may not have).
# 2. It's fast and fully isolated: every test runs inside a transaction
#    that's rolled back, with no risk of leaving data in a real database
#    (unlike the manual create/cleanup scripts used during development).
if "test" in sys.argv:
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": ":memory:",
    }

# See construction/test_runner.py's docstring: without this, plain
# `manage.py test` (no extra flags) fails because apps/ is both a real
# Python package (apps/__init__.py) and reachable via the sys.path
# insert above under each app's short name -- discovery needs to be
# told which of the two import paths to use.
TEST_RUNNER = 'construction.test_runner.AppsDirTestRunner'


# Supabase Storage (company logo upload). SUPABASE_URL is derived from the
# project ref (https://<ref>.supabase.co); SUPABASE_ANON_KEY comes from
# Project Settings -> API -> anon public key. Both are read from .env and
# are only needed for the runtime logo upload in company_settings -- the
# fallback public display path (company_logo context processor) does not
# require them.
SUPABASE_URL = os.getenv("SUPABASE_URL", "").rstrip("/")
SUPABASE_ANON_KEY = os.getenv("SUPABASE_ANON_KEY", "")
SUPABASE_LOGO_BUCKET = os.getenv("SUPABASE_LOGO_BUCKET", "logo")


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Argon2 only — all new passwords are hashed with Argon2. Existing passwords
# hashed with other algorithms (PBKDF2, bcrypt) will fail until reset.
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

# The live database's timestamp columns are all TIMESTAMP (no timezone),
# not TIMESTAMPTZ -- so Django's normal USE_TZ=True aware-datetime
# handling round-trips values as naive on every read, which then trips
# "naive datetime" RuntimeWarnings (and semantically wrong re-saves) on
# any full-instance update. False matches the DB exactly as provisioned;
# combined with TIME_ZONE='UTC' above, all datetimes are naive but
# consistently mean UTC throughout the app -- equivalent in practice to
# aware-UTC, just without Django's aware-datetime machinery fighting the
# schema. Revisit only if the live TIMESTAMP columns are ever migrated to
# TIMESTAMPTZ (a separate, cross-cutting schema change, not done here).
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# User-uploaded files (documents app, CPMAS-25). Local disk storage --
# there's no S3/Supabase Storage integration in this project yet, and
# adding one isn't in scope for this ticket; MEDIA_ROOT is git-ignored.
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'landing'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email (SMTP)
# https://docs.djangoproject.com/en/5.2/ref/settings/#email-backend
#
# Used by the auth flow to email password-reset links. Values come from env
# so credentials are never committed; see .env.example. EMAIL_BACKEND may be
# overridden to django.core.mail.backends.console.EmailBackend for local
# testing without a real SMTP server.
EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend'
)
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in ('1', 'true', 'yes', 'on')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'no-reply@localhost')

# Base URL of the frontend password-reset page; the reset link appends
# ?uid=...&token=... to it. Served by the Django reset-password view at
# /accounts/reset-password/ (see apps/core).
PASSWORD_RESET_BASE_URL = os.getenv('PASSWORD_RESET_BASE_URL', 'http://localhost:8000/accounts/reset-password')

# How long a password-reset token stays valid (Django's default: 3 days).
PASSWORD_RESET_TIMEOUT = int(os.getenv('PASSWORD_RESET_TIMEOUT', '259200'))


# Django REST Framework
# https://www.django-rest-framework.org/api-guide/settings/
#
# BRD 13.1 (Security) requires API authentication and permission checks on
# every endpoint. Authentication uses JWT (djangorestframework-simplejwt):
# clients send a Bearer token in the Authorization header; the token is
# signed with HMAC-SHA256 using SECRET_KEY and contains the user's ID.
# DRF's IsAuthenticated default stays on until role-specific permission
# classes (users.permissions: IsOwner / IsAccountant) are applied per-view.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'users.authentication.JwtUserAuthentication',
        'users.authentication.JwtCookieAuthentication',
        'users.authentication.UserSessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 25,
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# SimpleJWT configuration
# https://django-rest-framework-simplejwt.readthedocs.io/en/latest/settings.html
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# JWT placed in HttpOnly cookies (see users.authentication). Secure defaults
# to False so local HTTP development works; set JWT_COOKIE_SECURE=True and
# appropriate SameSite for production (HTTPS).
JWT_COOKIE_SECURE = os.getenv('JWT_COOKIE_SECURE', '').lower() in ('1', 'true', 'yes', 'on')
JWT_COOKIE_SAMESITE = os.getenv('JWT_COOKIE_SAMESITE', 'Lax')
