"""
Initial migration for the ``taxes`` app.

Creates ``tax_rates``. Built ahead of the dedicated Tax Management ticket
solely as a foreign-key target for ``inventory.Material.tax_rate``
(CPMAS-28); no other app depends on this migration yet.

Auto-generated by ``manage.py makemigrations`` on 2026-08-31; left as
generated, do not hand-edit the field definitions -- only this docstring
was added on top.
"""
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=8)),
                ('tax_type', models.CharField(max_length=50)),
                ('effective_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tax Rate',
                'verbose_name_plural': 'Tax Rates',
                'db_table': 'tax_rates',
                'ordering': ['name', '-effective_date'],
            },
        ),
    ]
