"""
Initial migration for the ``accounting`` app.

Creates ``accounts``, ``financial_transactions``, and
``transaction_lines`` (CPMAS-34: Accounting / Financial Transactions).
Depends on clients, projects, suppliers, and users' initial migrations
for their respective foreign-key targets.

Field set and constraints (including the two CHECK constraints on
transaction_lines, mirrored at the serializer layer -- see
TransactionLineSerializer.validate -- and the created_by column having
no _id suffix, same quirk as PurchaseOrder/Expense) were verified
against the live Supabase database before this migration was written,
since all three tables already exist there. Applied there with
``--fake-initial`` rather than executed, since the tables pre-exist; it
still runs normally (creates the tables) on any fresh environment.

Auto-generated by ``manage.py makemigrations``; do not hand-edit the
field definitions -- only this docstring was added on top.
"""
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('projects', '0001_initial'),
        ('suppliers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('parent_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_accounts', to='accounting.account')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'db_table': 'accounts',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_number', models.CharField(max_length=100, unique=True)),
                ('transaction_date', models.DateField()),
                ('description', models.TextField()),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('VOIDED', 'Voided')], db_index=True, default='DRAFT', max_length=20)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='clients.client')),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='financial_transactions_created', to='users.user')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='projects.project')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Financial Transaction',
                'verbose_name_plural': 'Financial Transactions',
                'db_table': 'financial_transactions',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_lines', to='accounting.account')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_lines', to='projects.project')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.financialtransaction')),
            ],
            options={
                'verbose_name': 'Transaction Line',
                'verbose_name_plural': 'Transaction Lines',
                'db_table': 'transaction_lines',
                'ordering': ['id'],
            },
        ),
    ]
