"""
Initial migration for the ``payments`` app: Payment, PaymentAllocation,
Receipt (CPMAS-35 -- Accounts Receivable & Accounts Payable).

All three tables (``payments``, ``payment_allocations``, ``receipts``)
already exist in the live Supabase database, provisioned by the
canonical SQL script ahead of this app owning them. Applied against the
live database with ``--fake-initial`` (structure already matches); runs
normally (creates the tables) on any fresh environment, e.g. the
in-memory SQLite test DB.

Auto-generated by ``manage.py makemigrations``; do not hand-edit the
field definitions -- only this docstring was added on top.
"""
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('invoicing', '0002_clientinvoice_clientinvoiceitem'),
        ('suppliers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_number', models.CharField(max_length=100, unique=True)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('direction', models.CharField(choices=[('INCOMING', 'Incoming'), ('OUTGOING', 'Outgoing')], db_index=True, max_length=20)),
                ('payment_method', models.CharField(max_length=50)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='clients.client')),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='payments_created', to='users.user')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('client_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='invoicing.clientinvoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='payments.payment')),
                ('supplier_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='invoicing.supplierinvoice')),
            ],
            options={
                'verbose_name': 'Payment Allocation',
                'verbose_name_plural': 'Payment Allocations',
                'db_table': 'payment_allocations',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(max_length=100, unique=True)),
                ('receipt_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'db_table': 'receipts',
                'ordering': ['-receipt_date', '-created_at'],
            },
        ),
    ]
