"""
Initial migration for the ``suppliers`` app.

Creates ``suppliers``. Built ahead of the dedicated Supplier Management
ticket solely as a foreign-key target for
``inventory.Material.default_supplier`` (CPMAS-28); ``inventory``'s initial
migration depends on this one.

Auto-generated by ``manage.py makemigrations`` on 2026-08-31; left as
generated, do not hand-edit the field definitions -- only this docstring
was added on top.
"""
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('tax_number', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'db_table': 'suppliers',
                'ordering': ['name'],
            },
        ),
    ]
