"""
Initial migration for the ``inventory`` app.

Creates ``material_categories`` and ``materials`` (CPMAS-28: Material
Management). Depends on ``suppliers.0001_initial`` and ``taxes.0001_initial``
because ``Material.default_supplier`` and ``Material.tax_rate`` are foreign
keys into those apps' tables, which must exist first.

Field set was reconciled against the shared Supabase database on
2026-08-31, where both tables already exist (provisioned directly via SQL
ahead of any Django migration) -- including the unique constraint on
``material_categories.name`` and the created_at/updated_at audit columns
on ``materials``. This migration is applied there with ``--fake-initial``
rather than executed, since the tables pre-exist; it still runs normally
(creates the tables) on any fresh environment.

Auto-generated by ``manage.py makemigrations``; do not hand-edit the field
definitions -- only this docstring was added on top.
"""
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Material Category',
                'verbose_name_plural': 'Material Categories',
                'db_table': 'material_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('unit', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('standard_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('minimum_stock_level', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_materials', to='suppliers.supplier')),
                ('tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='taxes.taxrate')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='inventory.materialcategory')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'db_table': 'materials',
                'ordering': ['name'],
            },
        ),
    ]
