"""
Initial migration for the ``invoicing`` app.

Creates ``supplier_invoices`` and ``supplier_invoice_items`` (CPMAS-32:
Supplier Invoices). Depends on suppliers, taxes, purchasing, and
inventory's initial migrations for their respective foreign-key targets.

Field set and constraints (including the CASCADE on
supplier_invoice_items.supplier_invoice and the UNIQUE on
supplier_invoices.invoice_number) were verified against the live
Supabase database before this migration was written, since both tables
already exist there. Applied there with ``--fake-initial`` rather than
executed, since the tables pre-exist; it still runs normally (creates
the tables) on any fresh environment.

Auto-generated by ``manage.py makemigrations``; do not hand-edit the
field definitions -- only this docstring was added on top.
"""
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_alter_stockmovement_movement_date'),
        ('purchasing', '0004_alter_purchaseorder_status'),
        ('suppliers', '0001_initial'),
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices', to='purchasing.purchaseorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Invoice',
                'verbose_name_plural': 'Supplier Invoices',
                'db_table': 'supplier_invoices',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoice_items', to='inventory.material')),
                ('supplier_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoicing.supplierinvoice')),
                ('tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoice_items', to='taxes.taxrate')),
            ],
            options={
                'verbose_name': 'Supplier Invoice Item',
                'verbose_name_plural': 'Supplier Invoice Items',
                'db_table': 'supplier_invoice_items',
                'ordering': ['id'],
            },
        ),
    ]
