"""
Migration for the ``invoicing`` app: adds ClientInvoice/ClientInvoiceItem
(CPMAS-35 -- Accounts Receivable & Accounts Payable).

Both tables (``client_invoices``, ``client_invoice_items``) already
exist in the live Supabase database, provisioned by the canonical SQL
script ahead of this app owning them. Applied against the live database
with ``--fake`` (structure already matches); runs normally (creates the
tables) on any fresh environment, e.g. the in-memory SQLite test DB.

Auto-generated by ``manage.py makemigrations``; do not hand-edit the
field definitions -- only this docstring was added on top.
"""
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('invoicing', '0001_initial'),
        ('projects', '0001_initial'),
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_invoices', to='clients.client')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_invoices', to='projects.project')),
            ],
            options={
                'verbose_name': 'Client Invoice',
                'verbose_name_plural': 'Client Invoices',
                'db_table': 'client_invoices',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientInvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('client_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoicing.clientinvoice')),
                ('tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_invoice_items', to='taxes.taxrate')),
            ],
            options={
                'verbose_name': 'Client Invoice Item',
                'verbose_name_plural': 'Client Invoice Items',
                'db_table': 'client_invoice_items',
                'ordering': ['id'],
            },
        ),
    ]
