"""
Migration for the ``expenses`` app: adds ExpenseCategory.account.

Closes a deferred foreign key from CPMAS-33 -- expense_categories.account_id
was already present in the live database's schema, but the Accounting
app (CPMAS-34, which owns accounting.Account) didn't exist yet at the
time, so this field was intentionally omitted. Applied against the live
Supabase database with ``--fake`` (the column already exists there);
runs normally (adds the column) on any fresh environment.

Auto-generated by ``manage.py makemigrations``; do not hand-edit the
field definition -- only this docstring was added on top.
"""
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_categories', to='accounting.account'),
        ),
    ]
