"""
Initial migration for the ``notifications`` app: Notification (CPMAS-22
-- System Notifications).

The ``notifications`` table already exists in the live Supabase
database, provisioned by the canonical SQL script ahead of this app
owning it. Applied against the live database with ``--fake-initial``
(structure already matches); runs normally (creates the table) on any
fresh environment, e.g. the in-memory SQLite test DB.

Auto-generated by ``manage.py makemigrations``; do not hand-edit the
field definitions -- only this docstring was added on top.
"""
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('entity_type', models.CharField(blank=True, max_length=100, null=True)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='users.user')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
